// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // To avoid Git lint issue
  static const senderId = '278276856991';
  static const t = 'pnsvn924p5g67h0kutfi72el9imlacel';

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_WEB'),
    appId: dotenv.get('FIREBASE_API_ID_WEB'),
    messagingSenderId: senderId,
    projectId: 'rjc-codelab-6',
    authDomain: 'rjc-codelab-6.firebaseapp.com',
    storageBucket: 'rjc-codelab-6.appspot.com',
    measurementId: 'G-07N9J4FP7Z',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_ANDROID'),
    appId: dotenv.get('FIREBASE_API_ID_ANDROID'),
    messagingSenderId: senderId,
    projectId: 'rjc-codelab-6',
    storageBucket: 'rjc-codelab-6.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_IOS'),
    appId: dotenv.get('FIREBASE_API_ID_IOS'),
    messagingSenderId: senderId,
    projectId: 'rjc-codelab-6',
    storageBucket: 'rjc-codelab-6.appspot.com',
    iosClientId: '$senderId-$t.apps.googleusercontent.com',
    iosBundleId: 'com.saifymatteo.rjc-codelab-6',
  );
}
