name: rjc_codelab_6

on: [pull_request, push]

# env:
#   FIREBASE_API_KEY_WEB=${{ secrets.FIREBASE_API_KEY_WEB }}
#   FIREBASE_APP_ID_WEB=${{ secrets.FIREBASE_APP_ID_WEB }}
#   FIREBASE_API_KEY_ANDROID=${{ secrets.FIREBASE_API_KEY_ANDROID }}
#   FIREBASE_API_ID_ANDROID=${{ secrets.FIREBASE_API_ID_ANDROID }}
#   FIREBASE_API_KEY_IOS=${{ secrets.FIREBASE_API_KEY_IOS }}
#   FIREBASE_API_ID_IOS=${{ secrets.FIREBASE_API_ID_IOS }}  

jobs:
  # steps:
  #   - name: Create .env file
  #     run: |
  #       touch .env
  #       echo FIREBASE_API_KEY_WEB=${{ secrets.FIREBASE_API_KEY_WEB }} >> .env
  #       echo FIREBASE_APP_ID_WEB=${{ secrets.FIREBASE_APP_ID_WEB }} >> .env
  #       echo FIREBASE_API_KEY_ANDROID=${{ secrets.FIREBASE_API_KEY_ANDROID }} >> .env
  #       echo FIREBASE_API_ID_ANDROID=${{ secrets.FIREBASE_API_ID_ANDROID }} >> .env
  #       echo FIREBASE_API_KEY_IOS=${{ secrets.FIREBASE_API_KEY_IOS }} >> .env
  #       echo FIREBASE_API_ID_IOS=${{ secrets.FIREBASE_API_ID_IOS }} >> .env
  #       cat .env
  # get-env:
  #   steps:
  #     - name: Create .env file
  #       uses: falti/dotenv-action@v0.2.8
  create-env:
    uses: SpicyPizza/create-envfile@v1.3.0
    with:
      envkey_SECRET_KEY: ${{ secrets.FIREBASE_API_KEY_WEB }}
      envkey_SECRET_KEY: ${{ secrets.FIREBASE_APP_ID_WEB }}
      envkey_SECRET_KEY: ${{ secrets.FIREBASE_API_KEY_ANDROID }}
      envkey_SECRET_KEY: ${{ secrets.FIREBASE_API_ID_ANDROID }}
      envkey_SECRET_KEY: ${{ secrets.FIREBASE_API_KEY_IOS }}
      envkey_SECRET_KEY: ${{ secrets.FIREBASE_API_ID_IOS }}
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.0.0
    